---
- hosts: all
  become: yes
  vars:
    jenkins_version: "2.277.4"
    jenkins_hostname: ""
    jenkins_url: 192.168.0.102
    jenkins_port: 8080
    jenkins_admin: "vieskov"
    #jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"
    jenkins_config_owner: "jenkins"
    jenkins_config_group: "jenkins"
    jenkins_install_via: "apt" 
    jenkins_include_custom_files: false
            
                 
    
      
  roles:
    - emmetog.jenkins