---
- name: Install Apache Web Server on AMI Linux. Upload web page example
  hosts: all
  become: yes


  vars:
    source_file: index.html
    destin_file: /var/www/html


  tasks:

  - name: Check Linux distro
    debug: var=ansible_os_family

  - name: Install Apache Web Server on RedHat Family
    yum:  name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: Install Apache Web Server on Debian Family
    apt:  update_cache=yes name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: Copy index.html to target server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    #notify: Restart Apache

  - name: Start Apache and enable it during boot
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Start Apache and enable it during boot
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted
