---
- name: Install Apache Web Server on AMI Linux. Upload web page example
  hosts: all
  become: yes


  vars:
    source_dir: index.html
    destin_dir: /var/www/html


  tasks:

  - name: Check Linux distro
    debug: var=ansible_os_family

  - block: # For RedHat

    - name: Install Apache Web Server on RedHat Family
      yum:  name=httpd state=latest
      
    - name: Copy index.html to target server
      copy:  src={{ source file }}  dest={{ destin_file }}  mode=0555
      notify: Restart Apache RedHat

    - name: Start Apache and enable it during boot
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: #For Debian

    - name: Install Apache Web Server on Debian Family
      apt:  update_cache=yes name=apache2 state=latest
      
    - name: Copy index.html to target server
      copy:  src={{ source file }}  dest={{ destin_file }}  mode=0555
      notify: Restart Apache RedHat

    - name: Start Apache and enable it during boot
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"
  
  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    
